function onlinechess(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',r='/',xb='073AD6796A1E4E20215F9991E2B1146D.cache.html',wb='223968797071423B3922DB1FCB5DB5A1.cache.html',vb='5162B62A1D40904C19DC7F9F7997AFC0.cache.html',tb='5484C2A761187EDB9CAE3EB013D2DE50.cache.html',ub='5E7DC273525B39DA6AFE1D0977B499E9.cache.html',zb='67B1A10E70A7C77FAB41C39FD6E2A636.cache.html',bc='<script defer="defer">onlinechess.onInjectionDone(\'onlinechess\')<\/script>',fc='<script id="',A='=',q='?',C='Bad handler "',ac='DOMContentLoaded',o='SCRIPT',ec='__gwt_marker_onlinechess',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',dc='end',mb='gecko',ob='gecko1_8',yb='gwt.hybrid',Ab='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',Fb='head',rb='hosted.html?onlinechess',Eb='href',lb='ie6',kb='ie8',ab='iframe',t='img',bb="javascript:''",Bb='link',qb='loadExternalRefs',v='meta',eb='moduleRequested',cc='moduleStartup',jb='msie',w='name',m='onlinechess',gb='opera',db='position:absolute;width:0;height:0;border:none',Cb='rel',ib='safari',sb='selectingPermutation',x='startup',Db='stylesheet',pb='unknown',fb='user.agent',hb='webkit';var hc=window,k=document,gc=hc.__gwtStatsEvent?function(a){return hc.__gwtStatsEvent(a)}:null,Bc,rc,mc,lc=l,uc={},Ec=[],Ac=[],kc=[],xc,zc;gc&&gc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!hc.__gwt_stylesLoaded){hc.__gwt_stylesLoaded={}}if(!hc.__gwt_scriptsLoaded){hc.__gwt_scriptsLoaded={}}function qc(){var b=false;try{b=hc.external&&(hc.external.gwtOnLoad&&hc.location.search.indexOf(yb)==-1)}catch(a){}qc=function(){return b};return b}
function tc(){if(Bc&&rc){var c=k.getElementById(m);var b=c.contentWindow;if(qc()){b.__gwt_getProperty=function(a){return nc(a)}}onlinechess=null;b.gwtOnLoad(xc,m,lc);gc&&gc({moduleName:m,subSystem:x,evtGroup:cc,millis:(new Date()).getTime(),type:dc})}}
function oc(){var j,h=ec,i;k.write(fc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){lc=f(j.src)}if(lc==l){var e=k.getElementsByTagName(s);if(e.length>0){lc=e[e.length-1].href}else{lc=f(k.location.href)}}else if(lc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=lc+u;lc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function yc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}uc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{zc=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{xc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function Dc(d,e){var a=kc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function nc(d){var e=Ac[d](),b=Ec[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(zc){zc(d,a,e)}throw null}
var pc;function sc(){if(!pc){pc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);gc&&gc({moduleName:m,subSystem:x,evtGroup:cc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(lc+Cc)}}
Ac[fb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(gb)!=-1){return gb}else if(d.indexOf(hb)!=-1){return ib}else if(d.indexOf(jb)!=-1){if(document.documentMode>=8){return kb}else{var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){var e=b(c);if(e>=6000){return lb}}}}else if(d.indexOf(mb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return ob}return mb}return pb};Ec[fb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};onlinechess.onScriptLoad=function(){if(pc){rc=true;tc()}};onlinechess.onInjectionDone=function(){Bc=true;gc&&gc({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:dc});tc()};oc();var Cc;if(qc()){if(hc.external.initModule&&hc.external.initModule(m)){hc.location.reload();return}Cc=rb}yc();gc&&gc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:sb});if(!Cc){try{Dc([gb],tb);Dc([ib],ub);Dc([ob],vb);Dc([mb],wb);Dc([kb],xb);Dc([lb],zb);Cc=kc[nc(fb)]}catch(a){return}}var wc;function vc(){if(!mc){mc=true;if(!__gwt_stylesLoaded[Ab]){var a=k.createElement(Bb);__gwt_stylesLoaded[Ab]=a;a.setAttribute(Cb,Db);a.setAttribute(Eb,lc+Ab);k.getElementsByTagName(Fb)[0].appendChild(a)}tc();if(k.removeEventListener){k.removeEventListener(ac,vc,false)}if(wc){clearInterval(wc)}}}
if(k.addEventListener){k.addEventListener(ac,function(){sc();vc()},false)}var wc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){sc();vc()}},50);gc&&gc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:dc});gc&&gc({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:nb});k.write(bc)}
onlinechess();